// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseRequest.proto

package com.jsj.member.ob.dto.proto;

public final class BaseRequestOuterClass {
  private BaseRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jsj.member.ob.dto.proto.BaseRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string AppVersion = 1;</code>
     */
    boolean hasAppVersion();
    /**
     * <code>optional string AppVersion = 1;</code>
     */
    String getAppVersion();
    /**
     * <code>optional string AppVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();

    /**
     * <code>optional .com.jsj.member.ob.dto.proto.SourceWay SourceWay = 2 [default = SourceWayNoSetting];</code>
     */
    boolean hasSourceWay();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.SourceWay SourceWay = 2 [default = SourceWayNoSetting];</code>
     */
    SourceWayOuterClass.SourceWay getSourceWay();

    /**
     * <code>optional .com.jsj.member.ob.dto.proto.LanguageVersion LanguageVersion = 3 [default = CN];</code>
     */
    boolean hasLanguageVersion();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.LanguageVersion LanguageVersion = 3 [default = CN];</code>
     */
    LanguageVersionOuterClass.LanguageVersion getLanguageVersion();

    /**
     * <code>optional string TerminalExt = 4;</code>
     */
    boolean hasTerminalExt();
    /**
     * <code>optional string TerminalExt = 4;</code>
     */
    String getTerminalExt();
    /**
     * <code>optional string TerminalExt = 4;</code>
     */
    com.google.protobuf.ByteString
        getTerminalExtBytes();

    /**
     * <code>optional string RegistrationId = 5;</code>
     */
    boolean hasRegistrationId();
    /**
     * <code>optional string RegistrationId = 5;</code>
     */
    String getRegistrationId();
    /**
     * <code>optional string RegistrationId = 5;</code>
     */
    com.google.protobuf.ByteString
        getRegistrationIdBytes();

    /**
     * <code>optional string IMEI = 6;</code>
     */
    boolean hasIMEI();
    /**
     * <code>optional string IMEI = 6;</code>
     */
    String getIMEI();
    /**
     * <code>optional string IMEI = 6;</code>
     */
    com.google.protobuf.ByteString
        getIMEIBytes();

    /**
     * <code>optional int32 OpEmployeeID = 7 [default = 0];</code>
     */
    boolean hasOpEmployeeID();
    /**
     * <code>optional int32 OpEmployeeID = 7 [default = 0];</code>
     */
    int getOpEmployeeID();

    /**
     * <code>optional string Token = 8;</code>
     */
    boolean hasToken();
    /**
     * <code>optional string Token = 8;</code>
     */
    String getToken();
    /**
     * <code>optional string Token = 8;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>optional .com.jsj.member.ob.dto.proto.DataCommission DataCommission = 9 [default = DataCommissionNoSetting];</code>
     */
    boolean hasDataCommission();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.DataCommission DataCommission = 9 [default = DataCommissionNoSetting];</code>
     */
    DataCommissionOuterClass.DataCommission getDataCommission();

    /**
     * <code>optional int32 DeptID = 10 [default = 0];</code>
     */
    boolean hasDeptID();
    /**
     * <code>optional int32 DeptID = 10 [default = 0];</code>
     */
    int getDeptID();
  }
  /**
   * Protobuf type {@code com.jsj.member.ob.dto.proto.BaseRequest}
   */
  public static final class BaseRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.jsj.member.ob.dto.proto.BaseRequest)
      BaseRequestOrBuilder {
    // Use BaseRequest.newBuilder() to construct.
    private BaseRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseRequest defaultInstance;
    public static BaseRequest getDefaultInstance() {
      return defaultInstance;
    }

    public BaseRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              appVersion_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              SourceWayOuterClass.SourceWay value = SourceWayOuterClass.SourceWay.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                sourceWay_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              LanguageVersionOuterClass.LanguageVersion value = LanguageVersionOuterClass.LanguageVersion.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                languageVersion_ = value;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              terminalExt_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              registrationId_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              iMEI_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              opEmployeeID_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              token_ = bs;
              break;
            }
            case 72: {
              int rawValue = input.readEnum();
              DataCommissionOuterClass.DataCommission value = DataCommissionOuterClass.DataCommission.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(9, rawValue);
              } else {
                bitField0_ |= 0x00000100;
                dataCommission_ = value;
              }
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              deptID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.BaseRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_BaseRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jsj.member.ob.dto.proto.BaseRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_BaseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest.class, com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseRequest> PARSER =
        new com.google.protobuf.AbstractParser<BaseRequest>() {
      public BaseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<BaseRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int APPVERSION_FIELD_NUMBER = 1;
    private Object appVersion_;
    /**
     * <code>optional string AppVersion = 1;</code>
     */
    public boolean hasAppVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string AppVersion = 1;</code>
     */
    public String getAppVersion() {
      Object ref = appVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string AppVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      Object ref = appVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCEWAY_FIELD_NUMBER = 2;
    private SourceWayOuterClass.SourceWay sourceWay_;
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.SourceWay SourceWay = 2 [default = SourceWayNoSetting];</code>
     */
    public boolean hasSourceWay() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.SourceWay SourceWay = 2 [default = SourceWayNoSetting];</code>
     */
    public SourceWayOuterClass.SourceWay getSourceWay() {
      return sourceWay_;
    }

    public static final int LANGUAGEVERSION_FIELD_NUMBER = 3;
    private LanguageVersionOuterClass.LanguageVersion languageVersion_;
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.LanguageVersion LanguageVersion = 3 [default = CN];</code>
     */
    public boolean hasLanguageVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.LanguageVersion LanguageVersion = 3 [default = CN];</code>
     */
    public LanguageVersionOuterClass.LanguageVersion getLanguageVersion() {
      return languageVersion_;
    }

    public static final int TERMINALEXT_FIELD_NUMBER = 4;
    private Object terminalExt_;
    /**
     * <code>optional string TerminalExt = 4;</code>
     */
    public boolean hasTerminalExt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string TerminalExt = 4;</code>
     */
    public String getTerminalExt() {
      Object ref = terminalExt_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          terminalExt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string TerminalExt = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTerminalExtBytes() {
      Object ref = terminalExt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        terminalExt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGISTRATIONID_FIELD_NUMBER = 5;
    private Object registrationId_;
    /**
     * <code>optional string RegistrationId = 5;</code>
     */
    public boolean hasRegistrationId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string RegistrationId = 5;</code>
     */
    public String getRegistrationId() {
      Object ref = registrationId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          registrationId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string RegistrationId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRegistrationIdBytes() {
      Object ref = registrationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        registrationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMEI_FIELD_NUMBER = 6;
    private Object iMEI_;
    /**
     * <code>optional string IMEI = 6;</code>
     */
    public boolean hasIMEI() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string IMEI = 6;</code>
     */
    public String getIMEI() {
      Object ref = iMEI_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          iMEI_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string IMEI = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIMEIBytes() {
      Object ref = iMEI_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        iMEI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPEMPLOYEEID_FIELD_NUMBER = 7;
    private int opEmployeeID_;
    /**
     * <code>optional int32 OpEmployeeID = 7 [default = 0];</code>
     */
    public boolean hasOpEmployeeID() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 OpEmployeeID = 7 [default = 0];</code>
     */
    public int getOpEmployeeID() {
      return opEmployeeID_;
    }

    public static final int TOKEN_FIELD_NUMBER = 8;
    private Object token_;
    /**
     * <code>optional string Token = 8;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string Token = 8;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Token = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATACOMMISSION_FIELD_NUMBER = 9;
    private DataCommissionOuterClass.DataCommission dataCommission_;
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.DataCommission DataCommission = 9 [default = DataCommissionNoSetting];</code>
     */
    public boolean hasDataCommission() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.DataCommission DataCommission = 9 [default = DataCommissionNoSetting];</code>
     */
    public DataCommissionOuterClass.DataCommission getDataCommission() {
      return dataCommission_;
    }

    public static final int DEPTID_FIELD_NUMBER = 10;
    private int deptID_;
    /**
     * <code>optional int32 DeptID = 10 [default = 0];</code>
     */
    public boolean hasDeptID() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 DeptID = 10 [default = 0];</code>
     */
    public int getDeptID() {
      return deptID_;
    }

    private void initFields() {
      appVersion_ = "";
      sourceWay_ = SourceWayOuterClass.SourceWay.SourceWayNoSetting;
      languageVersion_ = LanguageVersionOuterClass.LanguageVersion.CN;
      terminalExt_ = "";
      registrationId_ = "";
      iMEI_ = "";
      opEmployeeID_ = 0;
      token_ = "";
      dataCommission_ = DataCommissionOuterClass.DataCommission.DataCommissionNoSetting;
      deptID_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAppVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, sourceWay_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, languageVersion_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTerminalExtBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getRegistrationIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getIMEIBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, opEmployeeID_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getTokenBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeEnum(9, dataCommission_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, deptID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAppVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, sourceWay_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, languageVersion_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTerminalExtBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getRegistrationIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getIMEIBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, opEmployeeID_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getTokenBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, dataCommission_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, deptID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jsj.member.ob.dto.proto.BaseRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jsj.member.ob.dto.proto.BaseRequest)
        com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jsj.member.ob.dto.proto.BaseRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_BaseRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jsj.member.ob.dto.proto.BaseRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_BaseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest.class, com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest.Builder.class);
      }

      // Construct using com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceWay_ = SourceWayOuterClass.SourceWay.SourceWayNoSetting;
        bitField0_ = (bitField0_ & ~0x00000002);
        languageVersion_ = LanguageVersionOuterClass.LanguageVersion.CN;
        bitField0_ = (bitField0_ & ~0x00000004);
        terminalExt_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        registrationId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        iMEI_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        opEmployeeID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        dataCommission_ = DataCommissionOuterClass.DataCommission.DataCommissionNoSetting;
        bitField0_ = (bitField0_ & ~0x00000100);
        deptID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jsj.member.ob.dto.proto.BaseRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_BaseRequest_descriptor;
      }

      public com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest getDefaultInstanceForType() {
        return com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest.getDefaultInstance();
      }

      public com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest build() {
        com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest buildPartial() {
        com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest result = new com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appVersion_ = appVersion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sourceWay_ = sourceWay_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.languageVersion_ = languageVersion_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.terminalExt_ = terminalExt_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.registrationId_ = registrationId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.iMEI_ = iMEI_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.opEmployeeID_ = opEmployeeID_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.dataCommission_ = dataCommission_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.deptID_ = deptID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest) {
          return mergeFrom((com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest other) {
        if (other == com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest.getDefaultInstance()) return this;
        if (other.hasAppVersion()) {
          bitField0_ |= 0x00000001;
          appVersion_ = other.appVersion_;
          onChanged();
        }
        if (other.hasSourceWay()) {
          setSourceWay(other.getSourceWay());
        }
        if (other.hasLanguageVersion()) {
          setLanguageVersion(other.getLanguageVersion());
        }
        if (other.hasTerminalExt()) {
          bitField0_ |= 0x00000008;
          terminalExt_ = other.terminalExt_;
          onChanged();
        }
        if (other.hasRegistrationId()) {
          bitField0_ |= 0x00000010;
          registrationId_ = other.registrationId_;
          onChanged();
        }
        if (other.hasIMEI()) {
          bitField0_ |= 0x00000020;
          iMEI_ = other.iMEI_;
          onChanged();
        }
        if (other.hasOpEmployeeID()) {
          setOpEmployeeID(other.getOpEmployeeID());
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000080;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasDataCommission()) {
          setDataCommission(other.getDataCommission());
        }
        if (other.hasDeptID()) {
          setDeptID(other.getDeptID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jsj.member.ob.dto.proto.BaseRequestOuterClass.BaseRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object appVersion_ = "";
      /**
       * <code>optional string AppVersion = 1;</code>
       */
      public boolean hasAppVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string AppVersion = 1;</code>
       */
      public String getAppVersion() {
        Object ref = appVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appVersion_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string AppVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        Object ref = appVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string AppVersion = 1;</code>
       */
      public Builder setAppVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string AppVersion = 1;</code>
       */
      public Builder clearAppVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appVersion_ = getDefaultInstance().getAppVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string AppVersion = 1;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appVersion_ = value;
        onChanged();
        return this;
      }

      private SourceWayOuterClass.SourceWay sourceWay_ = SourceWayOuterClass.SourceWay.SourceWayNoSetting;
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.SourceWay SourceWay = 2 [default = SourceWayNoSetting];</code>
       */
      public boolean hasSourceWay() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.SourceWay SourceWay = 2 [default = SourceWayNoSetting];</code>
       */
      public SourceWayOuterClass.SourceWay getSourceWay() {
        return sourceWay_;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.SourceWay SourceWay = 2 [default = SourceWayNoSetting];</code>
       */
      public Builder setSourceWay(SourceWayOuterClass.SourceWay value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        sourceWay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.SourceWay SourceWay = 2 [default = SourceWayNoSetting];</code>
       */
      public Builder clearSourceWay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceWay_ = SourceWayOuterClass.SourceWay.SourceWayNoSetting;
        onChanged();
        return this;
      }

      private LanguageVersionOuterClass.LanguageVersion languageVersion_ = LanguageVersionOuterClass.LanguageVersion.CN;
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.LanguageVersion LanguageVersion = 3 [default = CN];</code>
       */
      public boolean hasLanguageVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.LanguageVersion LanguageVersion = 3 [default = CN];</code>
       */
      public LanguageVersionOuterClass.LanguageVersion getLanguageVersion() {
        return languageVersion_;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.LanguageVersion LanguageVersion = 3 [default = CN];</code>
       */
      public Builder setLanguageVersion(LanguageVersionOuterClass.LanguageVersion value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        languageVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.LanguageVersion LanguageVersion = 3 [default = CN];</code>
       */
      public Builder clearLanguageVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        languageVersion_ = LanguageVersionOuterClass.LanguageVersion.CN;
        onChanged();
        return this;
      }

      private Object terminalExt_ = "";
      /**
       * <code>optional string TerminalExt = 4;</code>
       */
      public boolean hasTerminalExt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string TerminalExt = 4;</code>
       */
      public String getTerminalExt() {
        Object ref = terminalExt_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            terminalExt_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string TerminalExt = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTerminalExtBytes() {
        Object ref = terminalExt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          terminalExt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string TerminalExt = 4;</code>
       */
      public Builder setTerminalExt(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        terminalExt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string TerminalExt = 4;</code>
       */
      public Builder clearTerminalExt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        terminalExt_ = getDefaultInstance().getTerminalExt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string TerminalExt = 4;</code>
       */
      public Builder setTerminalExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        terminalExt_ = value;
        onChanged();
        return this;
      }

      private Object registrationId_ = "";
      /**
       * <code>optional string RegistrationId = 5;</code>
       */
      public boolean hasRegistrationId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string RegistrationId = 5;</code>
       */
      public String getRegistrationId() {
        Object ref = registrationId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            registrationId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string RegistrationId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRegistrationIdBytes() {
        Object ref = registrationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          registrationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string RegistrationId = 5;</code>
       */
      public Builder setRegistrationId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        registrationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string RegistrationId = 5;</code>
       */
      public Builder clearRegistrationId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        registrationId_ = getDefaultInstance().getRegistrationId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string RegistrationId = 5;</code>
       */
      public Builder setRegistrationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        registrationId_ = value;
        onChanged();
        return this;
      }

      private Object iMEI_ = "";
      /**
       * <code>optional string IMEI = 6;</code>
       */
      public boolean hasIMEI() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string IMEI = 6;</code>
       */
      public String getIMEI() {
        Object ref = iMEI_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            iMEI_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string IMEI = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIMEIBytes() {
        Object ref = iMEI_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          iMEI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string IMEI = 6;</code>
       */
      public Builder setIMEI(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        iMEI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string IMEI = 6;</code>
       */
      public Builder clearIMEI() {
        bitField0_ = (bitField0_ & ~0x00000020);
        iMEI_ = getDefaultInstance().getIMEI();
        onChanged();
        return this;
      }
      /**
       * <code>optional string IMEI = 6;</code>
       */
      public Builder setIMEIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        iMEI_ = value;
        onChanged();
        return this;
      }

      private int opEmployeeID_ ;
      /**
       * <code>optional int32 OpEmployeeID = 7 [default = 0];</code>
       */
      public boolean hasOpEmployeeID() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 OpEmployeeID = 7 [default = 0];</code>
       */
      public int getOpEmployeeID() {
        return opEmployeeID_;
      }
      /**
       * <code>optional int32 OpEmployeeID = 7 [default = 0];</code>
       */
      public Builder setOpEmployeeID(int value) {
        bitField0_ |= 0x00000040;
        opEmployeeID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 OpEmployeeID = 7 [default = 0];</code>
       */
      public Builder clearOpEmployeeID() {
        bitField0_ = (bitField0_ & ~0x00000040);
        opEmployeeID_ = 0;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <code>optional string Token = 8;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string Token = 8;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string Token = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Token = 8;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Token = 8;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000080);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Token = 8;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        token_ = value;
        onChanged();
        return this;
      }

      private DataCommissionOuterClass.DataCommission dataCommission_ = DataCommissionOuterClass.DataCommission.DataCommissionNoSetting;
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.DataCommission DataCommission = 9 [default = DataCommissionNoSetting];</code>
       */
      public boolean hasDataCommission() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.DataCommission DataCommission = 9 [default = DataCommissionNoSetting];</code>
       */
      public DataCommissionOuterClass.DataCommission getDataCommission() {
        return dataCommission_;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.DataCommission DataCommission = 9 [default = DataCommissionNoSetting];</code>
       */
      public Builder setDataCommission(DataCommissionOuterClass.DataCommission value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        dataCommission_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.DataCommission DataCommission = 9 [default = DataCommissionNoSetting];</code>
       */
      public Builder clearDataCommission() {
        bitField0_ = (bitField0_ & ~0x00000100);
        dataCommission_ = DataCommissionOuterClass.DataCommission.DataCommissionNoSetting;
        onChanged();
        return this;
      }

      private int deptID_ ;
      /**
       * <code>optional int32 DeptID = 10 [default = 0];</code>
       */
      public boolean hasDeptID() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 DeptID = 10 [default = 0];</code>
       */
      public int getDeptID() {
        return deptID_;
      }
      /**
       * <code>optional int32 DeptID = 10 [default = 0];</code>
       */
      public Builder setDeptID(int value) {
        bitField0_ |= 0x00000200;
        deptID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 DeptID = 10 [default = 0];</code>
       */
      public Builder clearDeptID() {
        bitField0_ = (bitField0_ & ~0x00000200);
        deptID_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jsj.member.ob.dto.proto.BaseRequest)
    }

    static {
      defaultInstance = new BaseRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jsj.member.ob.dto.proto.BaseRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jsj_member_ob_dto_proto_BaseRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jsj_member_ob_dto_proto_BaseRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021BaseRequest.proto\022\033com.jsj.member.ob.d" +
      "to.proto\032\017SourceWay.proto\032\025LanguageVersi" +
      "on.proto\032\024DataCommission.proto\"\217\003\n\013BaseR" +
      "equest\022\022\n\nAppVersion\030\001 \001(\t\022M\n\tSourceWay\030" +
      "\002 \001(\0162&.com.jsj.member.ob.dto.proto.Sour" +
      "ceWay:\022SourceWayNoSetting\022I\n\017LanguageVer" +
      "sion\030\003 \001(\0162,.com.jsj.member.ob.dto.proto" +
      ".LanguageVersion:\002CN\022\023\n\013TerminalExt\030\004 \001(" +
      "\t\022\026\n\016RegistrationId\030\005 \001(\t\022\014\n\004IMEI\030\006 \001(\t\022" +
      "\027\n\014OpEmployeeID\030\007 \001(\005:\0010\022\r\n\005Token\030\010 \001(\t\022",
      "\\\n\016DataCommission\030\t \001(\0162+.com.jsj.member" +
      ".ob.dto.proto.DataCommission:\027DataCommis" +
      "sionNoSetting\022\021\n\006DeptID\030\n \001(\005:\0010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SourceWayOuterClass.getDescriptor(),
          LanguageVersionOuterClass.getDescriptor(),
          DataCommissionOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_jsj_member_ob_dto_proto_BaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jsj_member_ob_dto_proto_BaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_jsj_member_ob_dto_proto_BaseRequest_descriptor,
        new String[] { "AppVersion", "SourceWay", "LanguageVersion", "TerminalExt", "RegistrationId", "IMEI", "OpEmployeeID", "Token", "DataCommission", "DeptID", });
    SourceWayOuterClass.getDescriptor();
    LanguageVersionOuterClass.getDescriptor();
    DataCommissionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
