// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardTypeEnum.proto

package com.jsj.member.ob.dto.proto;

public final class CardTypeEnumOuterClass {
  private CardTypeEnumOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.jsj.member.ob.dto.proto.CardTypeEnum}
   */
  public enum CardTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BankCard = 0;</code>
     */
    BankCard(0, 0),
    /**
     * <code>CreditCard = 1;</code>
     */
    CreditCard(1, 1),
    /**
     * <code>DebitCard = 2;</code>
     */
    DebitCard(2, 2),
    ;

    /**
     * <code>BankCard = 0;</code>
     */
    public static final int BankCard_VALUE = 0;
    /**
     * <code>CreditCard = 1;</code>
     */
    public static final int CreditCard_VALUE = 1;
    /**
     * <code>DebitCard = 2;</code>
     */
    public static final int DebitCard_VALUE = 2;


    public final int getNumber() { return value; }

    public static CardTypeEnum valueOf(int value) {
      switch (value) {
        case 0: return BankCard;
        case 1: return CreditCard;
        case 2: return DebitCard;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CardTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CardTypeEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CardTypeEnum>() {
            public CardTypeEnum findValueByNumber(int number) {
              return CardTypeEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.CardTypeEnumOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final CardTypeEnum[] VALUES = values();

    public static CardTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CardTypeEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jsj.member.ob.dto.proto.CardTypeEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CardTypeEnum.proto\022\033com.jsj.member.ob." +
      "dto.proto*;\n\014CardTypeEnum\022\014\n\010BankCard\020\000\022" +
      "\016\n\nCreditCard\020\001\022\r\n\tDebitCard\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
