// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompanyType.proto

package com.jsj.member.ob.dto.proto;

public final class CompanyTypeOuterClass {
  private CompanyTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.jsj.member.ob.dto.proto.CompanyType}
   */
  public enum CompanyType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UnKnow = 0;</code>
     */
    UnKnow(0, 0),
    /**
     * <code>Golden = 1;</code>
     */
    Golden(1, 1),
    /**
     * <code>HappyTravel = 2;</code>
     */
    HappyTravel(2, 2),
    ;

    /**
     * <code>UnKnow = 0;</code>
     */
    public static final int UnKnow_VALUE = 0;
    /**
     * <code>Golden = 1;</code>
     */
    public static final int Golden_VALUE = 1;
    /**
     * <code>HappyTravel = 2;</code>
     */
    public static final int HappyTravel_VALUE = 2;


    public final int getNumber() { return value; }

    public static CompanyType valueOf(int value) {
      switch (value) {
        case 0: return UnKnow;
        case 1: return Golden;
        case 2: return HappyTravel;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CompanyType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CompanyType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CompanyType>() {
            public CompanyType findValueByNumber(int number) {
              return CompanyType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.CompanyTypeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final CompanyType[] VALUES = values();

    public static CompanyType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CompanyType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jsj.member.ob.dto.proto.CompanyType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021CompanyType.proto\022\033com.jsj.member.ob.d" +
      "to.proto*6\n\013CompanyType\022\n\n\006UnKnow\020\000\022\n\n\006G" +
      "olden\020\001\022\017\n\013HappyTravel\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
