// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerInformationResponse.proto

package com.jsj.member.ob.dto.proto;

public final class CustomerInformationResponseOuterClass {
  private CustomerInformationResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomerInformationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jsj.member.ob.dto.proto.CustomerInformationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
     */
    boolean hasBaseResponse();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
     */
    BaseResponseOuterClass.BaseResponse getBaseResponse();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
     */
    BaseResponseOuterClass.BaseResponseOrBuilder getBaseResponseOrBuilder();

    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    java.util.List<com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew>
        getListList();
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew getList(int index);
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    int getListCount();
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    java.util.List<? extends com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder>
        getListOrBuilderList();
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder getListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.jsj.member.ob.dto.proto.CustomerInformationResponse}
   */
  public static final class CustomerInformationResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.jsj.member.ob.dto.proto.CustomerInformationResponse)
      CustomerInformationResponseOrBuilder {
    // Use CustomerInformationResponse.newBuilder() to construct.
    private CustomerInformationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomerInformationResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomerInformationResponse defaultInstance;
    public static CustomerInformationResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CustomerInformationResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerInformationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              BaseResponseOuterClass.BaseResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = baseResponse_.toBuilder();
              }
              baseResponse_ = input.readMessage(BaseResponseOuterClass.BaseResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResponse_);
                baseResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                list_ = new java.util.ArrayList<com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew>();
                mutable_bitField0_ |= 0x00000002;
              }
              list_.add(input.readMessage(com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse.class, com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomerInformationResponse> PARSER =
        new com.google.protobuf.AbstractParser<CustomerInformationResponse>() {
      public CustomerInformationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerInformationResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CustomerInformationResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BASERESPONSE_FIELD_NUMBER = 1;
    private BaseResponseOuterClass.BaseResponse baseResponse_;
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
     */
    public BaseResponseOuterClass.BaseResponse getBaseResponse() {
      return baseResponse_;
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
     */
    public BaseResponseOuterClass.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      return baseResponse_;
    }

    public static final int LIST_FIELD_NUMBER = 2;
    private java.util.List<com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew> list_;
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    public java.util.List<com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew> getListList() {
      return list_;
    }
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    public java.util.List<? extends com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder>
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    public com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
     */
    public com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      baseResponse_ = BaseResponseOuterClass.BaseResponse.getDefaultInstance();
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, baseResponse_);
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(2, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, baseResponse_);
      }
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jsj.member.ob.dto.proto.CustomerInformationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jsj.member.ob.dto.proto.CustomerInformationResponse)
        com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse.class, com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse.Builder.class);
      }

      // Construct using com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBaseResponseFieldBuilder();
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (baseResponseBuilder_ == null) {
          baseResponse_ = BaseResponseOuterClass.BaseResponse.getDefaultInstance();
        } else {
          baseResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_descriptor;
      }

      public com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse getDefaultInstanceForType() {
        return com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse.getDefaultInstance();
      }

      public com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse build() {
        com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse buildPartial() {
        com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse result = new com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (baseResponseBuilder_ == null) {
          result.baseResponse_ = baseResponse_;
        } else {
          result.baseResponse_ = baseResponseBuilder_.build();
        }
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse) {
          return mergeFrom((com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse other) {
        if (other == com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse.getDefaultInstance()) return this;
        if (other.hasBaseResponse()) {
          mergeBaseResponse(other.getBaseResponse());
        }
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000002);
              listBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jsj.member.ob.dto.proto.CustomerInformationResponseOuterClass.CustomerInformationResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private BaseResponseOuterClass.BaseResponse baseResponse_ = BaseResponseOuterClass.BaseResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          BaseResponseOuterClass.BaseResponse, BaseResponseOuterClass.BaseResponse.Builder, BaseResponseOuterClass.BaseResponseOrBuilder> baseResponseBuilder_;
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      public boolean hasBaseResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      public BaseResponseOuterClass.BaseResponse getBaseResponse() {
        if (baseResponseBuilder_ == null) {
          return baseResponse_;
        } else {
          return baseResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      public Builder setBaseResponse(BaseResponseOuterClass.BaseResponse value) {
        if (baseResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResponse_ = value;
          onChanged();
        } else {
          baseResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      public Builder setBaseResponse(
          BaseResponseOuterClass.BaseResponse.Builder builderForValue) {
        if (baseResponseBuilder_ == null) {
          baseResponse_ = builderForValue.build();
          onChanged();
        } else {
          baseResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      public Builder mergeBaseResponse(BaseResponseOuterClass.BaseResponse value) {
        if (baseResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              baseResponse_ != BaseResponseOuterClass.BaseResponse.getDefaultInstance()) {
            baseResponse_ =
              BaseResponseOuterClass.BaseResponse.newBuilder(baseResponse_).mergeFrom(value).buildPartial();
          } else {
            baseResponse_ = value;
          }
          onChanged();
        } else {
          baseResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      public Builder clearBaseResponse() {
        if (baseResponseBuilder_ == null) {
          baseResponse_ = BaseResponseOuterClass.BaseResponse.getDefaultInstance();
          onChanged();
        } else {
          baseResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      public BaseResponseOuterClass.BaseResponse.Builder getBaseResponseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBaseResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      public BaseResponseOuterClass.BaseResponseOrBuilder getBaseResponseOrBuilder() {
        if (baseResponseBuilder_ != null) {
          return baseResponseBuilder_.getMessageOrBuilder();
        } else {
          return baseResponse_;
        }
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseResponse BaseResponse = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          BaseResponseOuterClass.BaseResponse, BaseResponseOuterClass.BaseResponse.Builder, BaseResponseOuterClass.BaseResponseOrBuilder>
          getBaseResponseFieldBuilder() {
        if (baseResponseBuilder_ == null) {
          baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              BaseResponseOuterClass.BaseResponse, BaseResponseOuterClass.BaseResponse.Builder, BaseResponseOuterClass.BaseResponseOrBuilder>(
                  getBaseResponse(),
                  getParentForChildren(),
                  isClean());
          baseResponse_ = null;
        }
        return baseResponseBuilder_;
      }

      private java.util.List<com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          list_ = new java.util.ArrayList<com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew>(list_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder> listBuilder_;

      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public java.util.List<com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder setList(
          int index, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder setList(
          int index, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder addList(com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder addList(
          int index, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder addList(
          com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder addList(
          int index, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder addAllList(
          Iterable<? extends com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public java.util.List<? extends com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder>
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.getDefaultInstance());
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.getDefaultInstance());
      }
      /**
       * <code>repeated .com.jsj.member.ob.dto.proto.CustomerInfoNew list = 2;</code>
       */
      public java.util.List<com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder>
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder>
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNew.Builder, com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.CustomerInfoNewOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.jsj.member.ob.dto.proto.CustomerInformationResponse)
    }

    static {
      defaultInstance = new CustomerInformationResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jsj.member.ob.dto.proto.CustomerInformationResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!CustomerInformationResponse.proto\022\033com" +
      ".jsj.member.ob.dto.proto\032\022BaseResponse.p" +
      "roto\032\025CustomerInfoNew.proto\"\232\001\n\033Customer" +
      "InformationResponse\022?\n\014BaseResponse\030\001 \001(" +
      "\0132).com.jsj.member.ob.dto.proto.BaseResp" +
      "onse\022:\n\004list\030\002 \003(\0132,.com.jsj.member.ob.d" +
      "to.proto.CustomerInfoNew"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BaseResponseOuterClass.getDescriptor(),
          com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_jsj_member_ob_dto_proto_CustomerInformationResponse_descriptor,
        new String[] { "BaseResponse", "List", });
    BaseResponseOuterClass.getDescriptor();
    com.jsj.member.ob.dto.proto.CustomerInfoNewOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
