// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EServiceSource.proto

package com.jsj.member.ob.dto.proto;

public final class EServiceSourceOuterClass {
  private EServiceSourceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.jsj.member.ob.dto.proto.EServiceSource}
   */
  public enum EServiceSource
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ServiceSourceNotSet = 0;</code>
     */
    ServiceSourceNotSet(0, 0),
    /**
     * <code>PayCard = 1;</code>
     */
    PayCard(1, 1),
    /**
     * <code>RenewCard = 2;</code>
     */
    RenewCard(2, 2),
    /**
     * <code>Flight = 3;</code>
     */
    Flight(3, 3),
    /**
     * <code>Hotel = 4;</code>
     */
    Hotel(4, 4),
    /**
     * <code>Train = 5;</code>
     */
    Train(5, 5),
    /**
     * <code>ShuttleBus = 6;</code>
     */
    ShuttleBus(6, 6),
    /**
     * <code>Activity = 7;</code>
     */
    Activity(7, 7),
    /**
     * <code>StrictChoice2 = 8;</code>
     */
    StrictChoice2(8, 8),
    ;

    /**
     * <code>ServiceSourceNotSet = 0;</code>
     */
    public static final int ServiceSourceNotSet_VALUE = 0;
    /**
     * <code>PayCard = 1;</code>
     */
    public static final int PayCard_VALUE = 1;
    /**
     * <code>RenewCard = 2;</code>
     */
    public static final int RenewCard_VALUE = 2;
    /**
     * <code>Flight = 3;</code>
     */
    public static final int Flight_VALUE = 3;
    /**
     * <code>Hotel = 4;</code>
     */
    public static final int Hotel_VALUE = 4;
    /**
     * <code>Train = 5;</code>
     */
    public static final int Train_VALUE = 5;
    /**
     * <code>ShuttleBus = 6;</code>
     */
    public static final int ShuttleBus_VALUE = 6;
    /**
     * <code>Activity = 7;</code>
     */
    public static final int Activity_VALUE = 7;
    /**
     * <code>StrictChoice2 = 8;</code>
     */
    public static final int StrictChoice2_VALUE = 8;


    public final int getNumber() { return value; }

    public static EServiceSource valueOf(int value) {
      switch (value) {
        case 0: return ServiceSourceNotSet;
        case 1: return PayCard;
        case 2: return RenewCard;
        case 3: return Flight;
        case 4: return Hotel;
        case 5: return Train;
        case 6: return ShuttleBus;
        case 7: return Activity;
        case 8: return StrictChoice2;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EServiceSource>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EServiceSource>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EServiceSource>() {
            public EServiceSource findValueByNumber(int number) {
              return EServiceSource.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.EServiceSourceOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final EServiceSource[] VALUES = values();

    public static EServiceSource valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EServiceSource(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jsj.member.ob.dto.proto.EServiceSource)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024EServiceSource.proto\022\033com.jsj.member.o" +
      "b.dto.proto*\230\001\n\016EServiceSource\022\027\n\023Servic" +
      "eSourceNotSet\020\000\022\013\n\007PayCard\020\001\022\r\n\tRenewCar" +
      "d\020\002\022\n\n\006Flight\020\003\022\t\n\005Hotel\020\004\022\t\n\005Train\020\005\022\016\n" +
      "\nShuttleBus\020\006\022\014\n\010Activity\020\007\022\021\n\rStrictCho" +
      "ice2\020\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
