// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LanguageVersion.proto

package com.jsj.member.ob.dto.proto;

public final class LanguageVersionOuterClass {
  private LanguageVersionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.jsj.member.ob.dto.proto.LanguageVersion}
   */
  public enum LanguageVersion
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CN = 0;</code>
     */
    CN(0, 0),
    /**
     * <code>EN = 1;</code>
     */
    EN(1, 1),
    ;

    /**
     * <code>CN = 0;</code>
     */
    public static final int CN_VALUE = 0;
    /**
     * <code>EN = 1;</code>
     */
    public static final int EN_VALUE = 1;


    public final int getNumber() { return value; }

    public static LanguageVersion valueOf(int value) {
      switch (value) {
        case 0: return CN;
        case 1: return EN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LanguageVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LanguageVersion>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LanguageVersion>() {
            public LanguageVersion findValueByNumber(int number) {
              return LanguageVersion.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.LanguageVersionOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final LanguageVersion[] VALUES = values();

    public static LanguageVersion valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LanguageVersion(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jsj.member.ob.dto.proto.LanguageVersion)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025LanguageVersion.proto\022\033com.jsj.member." +
      "ob.dto.proto*!\n\017LanguageVersion\022\006\n\002CN\020\000\022" +
      "\006\n\002EN\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
