// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayMethodEnum.proto

package com.jsj.member.ob.dto.proto;

public final class PayMethodEnumOuterClass {
  private PayMethodEnumOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.jsj.member.ob.dto.proto.PayMethodEnum}
   */
  public enum PayMethodEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PayMethodEnum_Unknown = 0;</code>
     */
    PayMethodEnum_Unknown(0, 0),
    /**
     * <code>NetBank = 1;</code>
     */
    NetBank(1, 1),
    /**
     * <code>IVR = 2;</code>
     */
    IVR(2, 2),
    /**
     * <code>BankTransfer = 4;</code>
     */
    BankTransfer(3, 4),
    /**
     * <code>QuickPay = 6;</code>
     */
    QuickPay(4, 6),
    /**
     * <code>NoCard = 7;</code>
     */
    NoCard(5, 7),
    /**
     * <code>ThirdAccount = 8;</code>
     */
    ThirdAccount(6, 8),
    /**
     * <code>NetBankWap = 9;</code>
     */
    NetBankWap(7, 9),
    /**
     * <code>WechatApp = 21;</code>
     */
    WechatApp(8, 21),
    /**
     * <code>WechatWeb = 22;</code>
     */
    WechatWeb(9, 22),
    /**
     * <code>WechatNative = 23;</code>
     */
    WechatNative(10, 23),
    /**
     * <code>WechatWap = 24;</code>
     */
    WechatWap(11, 24),
    /**
     * <code>AlipayApp = 31;</code>
     */
    AlipayApp(12, 31),
    /**
     * <code>AlipayWeb = 32;</code>
     */
    AlipayWeb(13, 32),
    /**
     * <code>AlipayWap = 33;</code>
     */
    AlipayWap(14, 33),
    /**
     * <code>UnionPayApp = 73;</code>
     */
    UnionPayApp(15, 73),
    /**
     * <code>AppleYeepayApp = 101;</code>
     */
    AppleYeepayApp(16, 101),
    /**
     * <code>AppleLianLianApp = 102;</code>
     */
    AppleLianLianApp(17, 102),
    /**
     * <code>AppleUnionPayApp = 103;</code>
     */
    AppleUnionPayApp(18, 103),
    /**
     * <code>SamsungPayApp = 111;</code>
     */
    SamsungPayApp(19, 111),
    /**
     * <code>MiPayApp = 121;</code>
     */
    MiPayApp(20, 121),
    ;

    /**
     * <code>PayMethodEnum_Unknown = 0;</code>
     */
    public static final int PayMethodEnum_Unknown_VALUE = 0;
    /**
     * <code>NetBank = 1;</code>
     */
    public static final int NetBank_VALUE = 1;
    /**
     * <code>IVR = 2;</code>
     */
    public static final int IVR_VALUE = 2;
    /**
     * <code>BankTransfer = 4;</code>
     */
    public static final int BankTransfer_VALUE = 4;
    /**
     * <code>QuickPay = 6;</code>
     */
    public static final int QuickPay_VALUE = 6;
    /**
     * <code>NoCard = 7;</code>
     */
    public static final int NoCard_VALUE = 7;
    /**
     * <code>ThirdAccount = 8;</code>
     */
    public static final int ThirdAccount_VALUE = 8;
    /**
     * <code>NetBankWap = 9;</code>
     */
    public static final int NetBankWap_VALUE = 9;
    /**
     * <code>WechatApp = 21;</code>
     */
    public static final int WechatApp_VALUE = 21;
    /**
     * <code>WechatWeb = 22;</code>
     */
    public static final int WechatWeb_VALUE = 22;
    /**
     * <code>WechatNative = 23;</code>
     */
    public static final int WechatNative_VALUE = 23;
    /**
     * <code>WechatWap = 24;</code>
     */
    public static final int WechatWap_VALUE = 24;
    /**
     * <code>AlipayApp = 31;</code>
     */
    public static final int AlipayApp_VALUE = 31;
    /**
     * <code>AlipayWeb = 32;</code>
     */
    public static final int AlipayWeb_VALUE = 32;
    /**
     * <code>AlipayWap = 33;</code>
     */
    public static final int AlipayWap_VALUE = 33;
    /**
     * <code>UnionPayApp = 73;</code>
     */
    public static final int UnionPayApp_VALUE = 73;
    /**
     * <code>AppleYeepayApp = 101;</code>
     */
    public static final int AppleYeepayApp_VALUE = 101;
    /**
     * <code>AppleLianLianApp = 102;</code>
     */
    public static final int AppleLianLianApp_VALUE = 102;
    /**
     * <code>AppleUnionPayApp = 103;</code>
     */
    public static final int AppleUnionPayApp_VALUE = 103;
    /**
     * <code>SamsungPayApp = 111;</code>
     */
    public static final int SamsungPayApp_VALUE = 111;
    /**
     * <code>MiPayApp = 121;</code>
     */
    public static final int MiPayApp_VALUE = 121;


    public final int getNumber() { return value; }

    public static PayMethodEnum valueOf(int value) {
      switch (value) {
        case 0: return PayMethodEnum_Unknown;
        case 1: return NetBank;
        case 2: return IVR;
        case 4: return BankTransfer;
        case 6: return QuickPay;
        case 7: return NoCard;
        case 8: return ThirdAccount;
        case 9: return NetBankWap;
        case 21: return WechatApp;
        case 22: return WechatWeb;
        case 23: return WechatNative;
        case 24: return WechatWap;
        case 31: return AlipayApp;
        case 32: return AlipayWeb;
        case 33: return AlipayWap;
        case 73: return UnionPayApp;
        case 101: return AppleYeepayApp;
        case 102: return AppleLianLianApp;
        case 103: return AppleUnionPayApp;
        case 111: return SamsungPayApp;
        case 121: return MiPayApp;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PayMethodEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PayMethodEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PayMethodEnum>() {
            public PayMethodEnum findValueByNumber(int number) {
              return PayMethodEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.PayMethodEnumOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final PayMethodEnum[] VALUES = values();

    public static PayMethodEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PayMethodEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jsj.member.ob.dto.proto.PayMethodEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PayMethodEnum.proto\022\033com.jsj.member.ob" +
      ".dto.proto*\354\002\n\rPayMethodEnum\022\031\n\025PayMetho" +
      "dEnum_Unknown\020\000\022\013\n\007NetBank\020\001\022\007\n\003IVR\020\002\022\020\n" +
      "\014BankTransfer\020\004\022\014\n\010QuickPay\020\006\022\n\n\006NoCard\020" +
      "\007\022\020\n\014ThirdAccount\020\010\022\016\n\nNetBankWap\020\t\022\r\n\tW" +
      "echatApp\020\025\022\r\n\tWechatWeb\020\026\022\020\n\014WechatNativ" +
      "e\020\027\022\r\n\tWechatWap\020\030\022\r\n\tAlipayApp\020\037\022\r\n\tAli" +
      "payWeb\020 \022\r\n\tAlipayWap\020!\022\017\n\013UnionPayApp\020I" +
      "\022\022\n\016AppleYeepayApp\020e\022\024\n\020AppleLianLianApp" +
      "\020f\022\024\n\020AppleUnionPayApp\020g\022\021\n\rSamsungPayAp",
      "p\020o\022\014\n\010MiPayApp\020y"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
