// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StrictChoiceConsumeRequest.proto

package com.jsj.member.ob.dto.proto;

public final class StrictChoiceConsumeRequestOuterClass {
  private StrictChoiceConsumeRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StrictChoiceConsumeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    boolean hasBaseRequest();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    BaseRequestOuterClass.BaseRequest getBaseRequest();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    BaseRequestOuterClass.BaseRequestOrBuilder getBaseRequestOrBuilder();

    /**
     * <code>optional int32 JSJID = 2 [default = 0];</code>
     */
    boolean hasJSJID();
    /**
     * <code>optional int32 JSJID = 2 [default = 0];</code>
     */
    int getJSJID();

    /**
     * <code>optional string OrderID = 3;</code>
     */
    boolean hasOrderID();
    /**
     * <code>optional string OrderID = 3;</code>
     */
    String getOrderID();
    /**
     * <code>optional string OrderID = 3;</code>
     */
    com.google.protobuf.ByteString
        getOrderIDBytes();

    /**
     * <code>optional double Money = 4 [default = 0];</code>
     */
    boolean hasMoney();
    /**
     * <code>optional double Money = 4 [default = 0];</code>
     */
    double getMoney();

    /**
     * <code>optional .com.jsj.member.ob.dto.proto.StrictChoiceOrderType OrderType = 5 [default = StrictChoiceOrderTypeUnSet];</code>
     */
    boolean hasOrderType();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.StrictChoiceOrderType OrderType = 5 [default = StrictChoiceOrderTypeUnSet];</code>
     */
    com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType getOrderType();

    /**
     * <code>optional int32 ProjectID = 6 [default = 0];</code>
     */
    boolean hasProjectID();
    /**
     * <code>optional int32 ProjectID = 6 [default = 0];</code>
     */
    int getProjectID();

    /**
     * <code>optional int32 DepositDeptID = 7 [default = 0];</code>
     */
    boolean hasDepositDeptID();
    /**
     * <code>optional int32 DepositDeptID = 7 [default = 0];</code>
     */
    int getDepositDeptID();

    /**
     * <code>optional string Remark = 8;</code>
     */
    boolean hasRemark();
    /**
     * <code>optional string Remark = 8;</code>
     */
    String getRemark();
    /**
     * <code>optional string Remark = 8;</code>
     */
    com.google.protobuf.ByteString
        getRemarkBytes();
  }
  /**
   * Protobuf type {@code com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequest}
   */
  public static final class StrictChoiceConsumeRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequest)
      StrictChoiceConsumeRequestOrBuilder {
    // Use StrictChoiceConsumeRequest.newBuilder() to construct.
    private StrictChoiceConsumeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StrictChoiceConsumeRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StrictChoiceConsumeRequest defaultInstance;
    public static StrictChoiceConsumeRequest getDefaultInstance() {
      return defaultInstance;
    }

    public StrictChoiceConsumeRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StrictChoiceConsumeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              BaseRequestOuterClass.BaseRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = baseRequest_.toBuilder();
              }
              baseRequest_ = input.readMessage(BaseRequestOuterClass.BaseRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseRequest_);
                baseRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jSJID_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              orderID_ = bs;
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              money_ = input.readDouble();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType value = com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                orderType_ = value;
              }
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              projectID_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              depositDeptID_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              remark_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest.class, com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<StrictChoiceConsumeRequest> PARSER =
        new com.google.protobuf.AbstractParser<StrictChoiceConsumeRequest>() {
      public StrictChoiceConsumeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StrictChoiceConsumeRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<StrictChoiceConsumeRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BASEREQUEST_FIELD_NUMBER = 1;
    private BaseRequestOuterClass.BaseRequest baseRequest_;
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    public boolean hasBaseRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    public BaseRequestOuterClass.BaseRequest getBaseRequest() {
      return baseRequest_;
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    public BaseRequestOuterClass.BaseRequestOrBuilder getBaseRequestOrBuilder() {
      return baseRequest_;
    }

    public static final int JSJID_FIELD_NUMBER = 2;
    private int jSJID_;
    /**
     * <code>optional int32 JSJID = 2 [default = 0];</code>
     */
    public boolean hasJSJID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 JSJID = 2 [default = 0];</code>
     */
    public int getJSJID() {
      return jSJID_;
    }

    public static final int ORDERID_FIELD_NUMBER = 3;
    private Object orderID_;
    /**
     * <code>optional string OrderID = 3;</code>
     */
    public boolean hasOrderID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string OrderID = 3;</code>
     */
    public String getOrderID() {
      Object ref = orderID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string OrderID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIDBytes() {
      Object ref = orderID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONEY_FIELD_NUMBER = 4;
    private double money_;
    /**
     * <code>optional double Money = 4 [default = 0];</code>
     */
    public boolean hasMoney() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double Money = 4 [default = 0];</code>
     */
    public double getMoney() {
      return money_;
    }

    public static final int ORDERTYPE_FIELD_NUMBER = 5;
    private com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType orderType_;
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.StrictChoiceOrderType OrderType = 5 [default = StrictChoiceOrderTypeUnSet];</code>
     */
    public boolean hasOrderType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.StrictChoiceOrderType OrderType = 5 [default = StrictChoiceOrderTypeUnSet];</code>
     */
    public com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType getOrderType() {
      return orderType_;
    }

    public static final int PROJECTID_FIELD_NUMBER = 6;
    private int projectID_;
    /**
     * <code>optional int32 ProjectID = 6 [default = 0];</code>
     */
    public boolean hasProjectID() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 ProjectID = 6 [default = 0];</code>
     */
    public int getProjectID() {
      return projectID_;
    }

    public static final int DEPOSITDEPTID_FIELD_NUMBER = 7;
    private int depositDeptID_;
    /**
     * <code>optional int32 DepositDeptID = 7 [default = 0];</code>
     */
    public boolean hasDepositDeptID() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 DepositDeptID = 7 [default = 0];</code>
     */
    public int getDepositDeptID() {
      return depositDeptID_;
    }

    public static final int REMARK_FIELD_NUMBER = 8;
    private Object remark_;
    /**
     * <code>optional string Remark = 8;</code>
     */
    public boolean hasRemark() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string Remark = 8;</code>
     */
    public String getRemark() {
      Object ref = remark_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remark_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Remark = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      baseRequest_ = BaseRequestOuterClass.BaseRequest.getDefaultInstance();
      jSJID_ = 0;
      orderID_ = "";
      money_ = 0D;
      orderType_ = com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType.StrictChoiceOrderTypeUnSet;
      projectID_ = 0;
      depositDeptID_ = 0;
      remark_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, baseRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, jSJID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getOrderIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, money_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, orderType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, projectID_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, depositDeptID_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getRemarkBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, baseRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, jSJID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOrderIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, money_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, orderType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, projectID_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, depositDeptID_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getRemarkBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequest)
        com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest.class, com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest.Builder.class);
      }

      // Construct using com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBaseRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (baseRequestBuilder_ == null) {
          baseRequest_ = BaseRequestOuterClass.BaseRequest.getDefaultInstance();
        } else {
          baseRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        jSJID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        orderID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        money_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        orderType_ = com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType.StrictChoiceOrderTypeUnSet;
        bitField0_ = (bitField0_ & ~0x00000010);
        projectID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        depositDeptID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        remark_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_descriptor;
      }

      public com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest getDefaultInstanceForType() {
        return com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest.getDefaultInstance();
      }

      public com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest build() {
        com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest buildPartial() {
        com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest result = new com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (baseRequestBuilder_ == null) {
          result.baseRequest_ = baseRequest_;
        } else {
          result.baseRequest_ = baseRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jSJID_ = jSJID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.orderID_ = orderID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.money_ = money_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.orderType_ = orderType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.projectID_ = projectID_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.depositDeptID_ = depositDeptID_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.remark_ = remark_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest) {
          return mergeFrom((com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest other) {
        if (other == com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest.getDefaultInstance()) return this;
        if (other.hasBaseRequest()) {
          mergeBaseRequest(other.getBaseRequest());
        }
        if (other.hasJSJID()) {
          setJSJID(other.getJSJID());
        }
        if (other.hasOrderID()) {
          bitField0_ |= 0x00000004;
          orderID_ = other.orderID_;
          onChanged();
        }
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        if (other.hasOrderType()) {
          setOrderType(other.getOrderType());
        }
        if (other.hasProjectID()) {
          setProjectID(other.getProjectID());
        }
        if (other.hasDepositDeptID()) {
          setDepositDeptID(other.getDepositDeptID());
        }
        if (other.hasRemark()) {
          bitField0_ |= 0x00000080;
          remark_ = other.remark_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequestOuterClass.StrictChoiceConsumeRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private BaseRequestOuterClass.BaseRequest baseRequest_ = BaseRequestOuterClass.BaseRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          BaseRequestOuterClass.BaseRequest, BaseRequestOuterClass.BaseRequest.Builder, BaseRequestOuterClass.BaseRequestOrBuilder> baseRequestBuilder_;
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public boolean hasBaseRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public BaseRequestOuterClass.BaseRequest getBaseRequest() {
        if (baseRequestBuilder_ == null) {
          return baseRequest_;
        } else {
          return baseRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public Builder setBaseRequest(BaseRequestOuterClass.BaseRequest value) {
        if (baseRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseRequest_ = value;
          onChanged();
        } else {
          baseRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public Builder setBaseRequest(
          BaseRequestOuterClass.BaseRequest.Builder builderForValue) {
        if (baseRequestBuilder_ == null) {
          baseRequest_ = builderForValue.build();
          onChanged();
        } else {
          baseRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public Builder mergeBaseRequest(BaseRequestOuterClass.BaseRequest value) {
        if (baseRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              baseRequest_ != BaseRequestOuterClass.BaseRequest.getDefaultInstance()) {
            baseRequest_ =
              BaseRequestOuterClass.BaseRequest.newBuilder(baseRequest_).mergeFrom(value).buildPartial();
          } else {
            baseRequest_ = value;
          }
          onChanged();
        } else {
          baseRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public Builder clearBaseRequest() {
        if (baseRequestBuilder_ == null) {
          baseRequest_ = BaseRequestOuterClass.BaseRequest.getDefaultInstance();
          onChanged();
        } else {
          baseRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public BaseRequestOuterClass.BaseRequest.Builder getBaseRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBaseRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public BaseRequestOuterClass.BaseRequestOrBuilder getBaseRequestOrBuilder() {
        if (baseRequestBuilder_ != null) {
          return baseRequestBuilder_.getMessageOrBuilder();
        } else {
          return baseRequest_;
        }
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          BaseRequestOuterClass.BaseRequest, BaseRequestOuterClass.BaseRequest.Builder, BaseRequestOuterClass.BaseRequestOrBuilder>
          getBaseRequestFieldBuilder() {
        if (baseRequestBuilder_ == null) {
          baseRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              BaseRequestOuterClass.BaseRequest, BaseRequestOuterClass.BaseRequest.Builder, BaseRequestOuterClass.BaseRequestOrBuilder>(
                  getBaseRequest(),
                  getParentForChildren(),
                  isClean());
          baseRequest_ = null;
        }
        return baseRequestBuilder_;
      }

      private int jSJID_ ;
      /**
       * <code>optional int32 JSJID = 2 [default = 0];</code>
       */
      public boolean hasJSJID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 JSJID = 2 [default = 0];</code>
       */
      public int getJSJID() {
        return jSJID_;
      }
      /**
       * <code>optional int32 JSJID = 2 [default = 0];</code>
       */
      public Builder setJSJID(int value) {
        bitField0_ |= 0x00000002;
        jSJID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 JSJID = 2 [default = 0];</code>
       */
      public Builder clearJSJID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jSJID_ = 0;
        onChanged();
        return this;
      }

      private Object orderID_ = "";
      /**
       * <code>optional string OrderID = 3;</code>
       */
      public boolean hasOrderID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string OrderID = 3;</code>
       */
      public String getOrderID() {
        Object ref = orderID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderID_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string OrderID = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIDBytes() {
        Object ref = orderID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orderID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string OrderID = 3;</code>
       */
      public Builder setOrderID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        orderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string OrderID = 3;</code>
       */
      public Builder clearOrderID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        orderID_ = getDefaultInstance().getOrderID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string OrderID = 3;</code>
       */
      public Builder setOrderIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        orderID_ = value;
        onChanged();
        return this;
      }

      private double money_ ;
      /**
       * <code>optional double Money = 4 [default = 0];</code>
       */
      public boolean hasMoney() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double Money = 4 [default = 0];</code>
       */
      public double getMoney() {
        return money_;
      }
      /**
       * <code>optional double Money = 4 [default = 0];</code>
       */
      public Builder setMoney(double value) {
        bitField0_ |= 0x00000008;
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double Money = 4 [default = 0];</code>
       */
      public Builder clearMoney() {
        bitField0_ = (bitField0_ & ~0x00000008);
        money_ = 0D;
        onChanged();
        return this;
      }

      private com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType orderType_ = com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType.StrictChoiceOrderTypeUnSet;
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.StrictChoiceOrderType OrderType = 5 [default = StrictChoiceOrderTypeUnSet];</code>
       */
      public boolean hasOrderType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.StrictChoiceOrderType OrderType = 5 [default = StrictChoiceOrderTypeUnSet];</code>
       */
      public com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType getOrderType() {
        return orderType_;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.StrictChoiceOrderType OrderType = 5 [default = StrictChoiceOrderTypeUnSet];</code>
       */
      public Builder setOrderType(com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        orderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.StrictChoiceOrderType OrderType = 5 [default = StrictChoiceOrderTypeUnSet];</code>
       */
      public Builder clearOrderType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        orderType_ = com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.StrictChoiceOrderType.StrictChoiceOrderTypeUnSet;
        onChanged();
        return this;
      }

      private int projectID_ ;
      /**
       * <code>optional int32 ProjectID = 6 [default = 0];</code>
       */
      public boolean hasProjectID() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 ProjectID = 6 [default = 0];</code>
       */
      public int getProjectID() {
        return projectID_;
      }
      /**
       * <code>optional int32 ProjectID = 6 [default = 0];</code>
       */
      public Builder setProjectID(int value) {
        bitField0_ |= 0x00000020;
        projectID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ProjectID = 6 [default = 0];</code>
       */
      public Builder clearProjectID() {
        bitField0_ = (bitField0_ & ~0x00000020);
        projectID_ = 0;
        onChanged();
        return this;
      }

      private int depositDeptID_ ;
      /**
       * <code>optional int32 DepositDeptID = 7 [default = 0];</code>
       */
      public boolean hasDepositDeptID() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 DepositDeptID = 7 [default = 0];</code>
       */
      public int getDepositDeptID() {
        return depositDeptID_;
      }
      /**
       * <code>optional int32 DepositDeptID = 7 [default = 0];</code>
       */
      public Builder setDepositDeptID(int value) {
        bitField0_ |= 0x00000040;
        depositDeptID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 DepositDeptID = 7 [default = 0];</code>
       */
      public Builder clearDepositDeptID() {
        bitField0_ = (bitField0_ & ~0x00000040);
        depositDeptID_ = 0;
        onChanged();
        return this;
      }

      private Object remark_ = "";
      /**
       * <code>optional string Remark = 8;</code>
       */
      public boolean hasRemark() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string Remark = 8;</code>
       */
      public String getRemark() {
        Object ref = remark_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            remark_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string Remark = 8;</code>
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Remark = 8;</code>
       */
      public Builder setRemark(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Remark = 8;</code>
       */
      public Builder clearRemark() {
        bitField0_ = (bitField0_ & ~0x00000080);
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Remark = 8;</code>
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        remark_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequest)
    }

    static {
      defaultInstance = new StrictChoiceConsumeRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jsj.member.ob.dto.proto.StrictChoiceConsumeRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n StrictChoiceConsumeRequest.proto\022\033com." +
      "jsj.member.ob.dto.proto\032\021BaseRequest.pro" +
      "to\032\033StrictChoiceOrderType.proto\"\263\002\n\032Stri" +
      "ctChoiceConsumeRequest\022=\n\013BaseRequest\030\001 " +
      "\001(\0132(.com.jsj.member.ob.dto.proto.BaseRe" +
      "quest\022\020\n\005JSJID\030\002 \001(\005:\0010\022\017\n\007OrderID\030\003 \001(\t" +
      "\022\020\n\005Money\030\004 \001(\001:\0010\022a\n\tOrderType\030\005 \001(\01622." +
      "com.jsj.member.ob.dto.proto.StrictChoice" +
      "OrderType:\032StrictChoiceOrderTypeUnSet\022\024\n" +
      "\tProjectID\030\006 \001(\005:\0010\022\030\n\rDepositDeptID\030\007 \001",
      "(\005:\0010\022\016\n\006Remark\030\010 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BaseRequestOuterClass.getDescriptor(),
          com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_jsj_member_ob_dto_proto_StrictChoiceConsumeRequest_descriptor,
        new String[] { "BaseRequest", "JSJID", "OrderID", "Money", "OrderType", "ProjectID", "DepositDeptID", "Remark", });
    BaseRequestOuterClass.getDescriptor();
    com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
