// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StrictChoiceOrderType.proto

package com.jsj.member.ob.dto.proto;

public final class StrictChoiceOrderTypeOuterClass {
  private StrictChoiceOrderTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.jsj.member.ob.dto.proto.StrictChoiceOrderType}
   */
  public enum StrictChoiceOrderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>StrictChoiceOrderTypeUnSet = 0;</code>
     */
    StrictChoiceOrderTypeUnSet(0, 0),
    /**
     * <code>StrictChoice = 1;</code>
     */
    StrictChoice(1, 1),
    ;

    /**
     * <code>StrictChoiceOrderTypeUnSet = 0;</code>
     */
    public static final int StrictChoiceOrderTypeUnSet_VALUE = 0;
    /**
     * <code>StrictChoice = 1;</code>
     */
    public static final int StrictChoice_VALUE = 1;


    public final int getNumber() { return value; }

    public static StrictChoiceOrderType valueOf(int value) {
      switch (value) {
        case 0: return StrictChoiceOrderTypeUnSet;
        case 1: return StrictChoice;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StrictChoiceOrderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StrictChoiceOrderType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StrictChoiceOrderType>() {
            public StrictChoiceOrderType findValueByNumber(int number) {
              return StrictChoiceOrderType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.StrictChoiceOrderTypeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final StrictChoiceOrderType[] VALUES = values();

    public static StrictChoiceOrderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private StrictChoiceOrderType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jsj.member.ob.dto.proto.StrictChoiceOrderType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033StrictChoiceOrderType.proto\022\033com.jsj.m" +
      "ember.ob.dto.proto*I\n\025StrictChoiceOrderT" +
      "ype\022\036\n\032StrictChoiceOrderTypeUnSet\020\000\022\020\n\014S" +
      "trictChoice\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
