// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StrictChoiceSearchRequest.proto

package com.jsj.member.ob.dto.proto;

public final class StrictChoiceSearchRequestOuterClass {
  private StrictChoiceSearchRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StrictChoiceSearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jsj.member.ob.dto.proto.StrictChoiceSearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    boolean hasBaseRequest();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    BaseRequestOuterClass.BaseRequest getBaseRequest();
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    BaseRequestOuterClass.BaseRequestOrBuilder getBaseRequestOrBuilder();

    /**
     * <code>optional int32 JSJID = 2 [default = 0];</code>
     */
    boolean hasJSJID();
    /**
     * <code>optional int32 JSJID = 2 [default = 0];</code>
     */
    int getJSJID();
  }
  /**
   * Protobuf type {@code com.jsj.member.ob.dto.proto.StrictChoiceSearchRequest}
   */
  public static final class StrictChoiceSearchRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.jsj.member.ob.dto.proto.StrictChoiceSearchRequest)
      StrictChoiceSearchRequestOrBuilder {
    // Use StrictChoiceSearchRequest.newBuilder() to construct.
    private StrictChoiceSearchRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StrictChoiceSearchRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StrictChoiceSearchRequest defaultInstance;
    public static StrictChoiceSearchRequest getDefaultInstance() {
      return defaultInstance;
    }

    public StrictChoiceSearchRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StrictChoiceSearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              BaseRequestOuterClass.BaseRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = baseRequest_.toBuilder();
              }
              baseRequest_ = input.readMessage(BaseRequestOuterClass.BaseRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseRequest_);
                baseRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jSJID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest.class, com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<StrictChoiceSearchRequest> PARSER =
        new com.google.protobuf.AbstractParser<StrictChoiceSearchRequest>() {
      public StrictChoiceSearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StrictChoiceSearchRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<StrictChoiceSearchRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BASEREQUEST_FIELD_NUMBER = 1;
    private BaseRequestOuterClass.BaseRequest baseRequest_;
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    public boolean hasBaseRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    public BaseRequestOuterClass.BaseRequest getBaseRequest() {
      return baseRequest_;
    }
    /**
     * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
     */
    public BaseRequestOuterClass.BaseRequestOrBuilder getBaseRequestOrBuilder() {
      return baseRequest_;
    }

    public static final int JSJID_FIELD_NUMBER = 2;
    private int jSJID_;
    /**
     * <code>optional int32 JSJID = 2 [default = 0];</code>
     */
    public boolean hasJSJID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 JSJID = 2 [default = 0];</code>
     */
    public int getJSJID() {
      return jSJID_;
    }

    private void initFields() {
      baseRequest_ = BaseRequestOuterClass.BaseRequest.getDefaultInstance();
      jSJID_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, baseRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, jSJID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, baseRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, jSJID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jsj.member.ob.dto.proto.StrictChoiceSearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jsj.member.ob.dto.proto.StrictChoiceSearchRequest)
        com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest.class, com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest.Builder.class);
      }

      // Construct using com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBaseRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (baseRequestBuilder_ == null) {
          baseRequest_ = BaseRequestOuterClass.BaseRequest.getDefaultInstance();
        } else {
          baseRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        jSJID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_descriptor;
      }

      public com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest getDefaultInstanceForType() {
        return com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest.getDefaultInstance();
      }

      public com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest build() {
        com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest buildPartial() {
        com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest result = new com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (baseRequestBuilder_ == null) {
          result.baseRequest_ = baseRequest_;
        } else {
          result.baseRequest_ = baseRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jSJID_ = jSJID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest) {
          return mergeFrom((com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest other) {
        if (other == com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest.getDefaultInstance()) return this;
        if (other.hasBaseRequest()) {
          mergeBaseRequest(other.getBaseRequest());
        }
        if (other.hasJSJID()) {
          setJSJID(other.getJSJID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jsj.member.ob.dto.proto.StrictChoiceSearchRequestOuterClass.StrictChoiceSearchRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private BaseRequestOuterClass.BaseRequest baseRequest_ = BaseRequestOuterClass.BaseRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          BaseRequestOuterClass.BaseRequest, BaseRequestOuterClass.BaseRequest.Builder, BaseRequestOuterClass.BaseRequestOrBuilder> baseRequestBuilder_;
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public boolean hasBaseRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public BaseRequestOuterClass.BaseRequest getBaseRequest() {
        if (baseRequestBuilder_ == null) {
          return baseRequest_;
        } else {
          return baseRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public Builder setBaseRequest(BaseRequestOuterClass.BaseRequest value) {
        if (baseRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseRequest_ = value;
          onChanged();
        } else {
          baseRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public Builder setBaseRequest(
          BaseRequestOuterClass.BaseRequest.Builder builderForValue) {
        if (baseRequestBuilder_ == null) {
          baseRequest_ = builderForValue.build();
          onChanged();
        } else {
          baseRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public Builder mergeBaseRequest(BaseRequestOuterClass.BaseRequest value) {
        if (baseRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              baseRequest_ != BaseRequestOuterClass.BaseRequest.getDefaultInstance()) {
            baseRequest_ =
              BaseRequestOuterClass.BaseRequest.newBuilder(baseRequest_).mergeFrom(value).buildPartial();
          } else {
            baseRequest_ = value;
          }
          onChanged();
        } else {
          baseRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public Builder clearBaseRequest() {
        if (baseRequestBuilder_ == null) {
          baseRequest_ = BaseRequestOuterClass.BaseRequest.getDefaultInstance();
          onChanged();
        } else {
          baseRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public BaseRequestOuterClass.BaseRequest.Builder getBaseRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBaseRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      public BaseRequestOuterClass.BaseRequestOrBuilder getBaseRequestOrBuilder() {
        if (baseRequestBuilder_ != null) {
          return baseRequestBuilder_.getMessageOrBuilder();
        } else {
          return baseRequest_;
        }
      }
      /**
       * <code>optional .com.jsj.member.ob.dto.proto.BaseRequest BaseRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          BaseRequestOuterClass.BaseRequest, BaseRequestOuterClass.BaseRequest.Builder, BaseRequestOuterClass.BaseRequestOrBuilder>
          getBaseRequestFieldBuilder() {
        if (baseRequestBuilder_ == null) {
          baseRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              BaseRequestOuterClass.BaseRequest, BaseRequestOuterClass.BaseRequest.Builder, BaseRequestOuterClass.BaseRequestOrBuilder>(
                  getBaseRequest(),
                  getParentForChildren(),
                  isClean());
          baseRequest_ = null;
        }
        return baseRequestBuilder_;
      }

      private int jSJID_ ;
      /**
       * <code>optional int32 JSJID = 2 [default = 0];</code>
       */
      public boolean hasJSJID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 JSJID = 2 [default = 0];</code>
       */
      public int getJSJID() {
        return jSJID_;
      }
      /**
       * <code>optional int32 JSJID = 2 [default = 0];</code>
       */
      public Builder setJSJID(int value) {
        bitField0_ |= 0x00000002;
        jSJID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 JSJID = 2 [default = 0];</code>
       */
      public Builder clearJSJID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jSJID_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jsj.member.ob.dto.proto.StrictChoiceSearchRequest)
    }

    static {
      defaultInstance = new StrictChoiceSearchRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jsj.member.ob.dto.proto.StrictChoiceSearchRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037StrictChoiceSearchRequest.proto\022\033com.j" +
      "sj.member.ob.dto.proto\032\021BaseRequest.prot" +
      "o\"l\n\031StrictChoiceSearchRequest\022=\n\013BaseRe" +
      "quest\030\001 \001(\0132(.com.jsj.member.ob.dto.prot" +
      "o.BaseRequest\022\020\n\005JSJID\030\002 \001(\005:\0010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BaseRequestOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_jsj_member_ob_dto_proto_StrictChoiceSearchRequest_descriptor,
        new String[] { "BaseRequest", "JSJID", });
    BaseRequestOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
