// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StrictChoices.proto

package com.jsj.member.ob.dto.proto;

public final class StrictChoicesOuterClass {
  private StrictChoicesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StrictChoicesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jsj.member.ob.dto.proto.StrictChoices)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string StradeName = 1;</code>
     */
    boolean hasStradeName();
    /**
     * <code>optional string StradeName = 1;</code>
     */
    String getStradeName();
    /**
     * <code>optional string StradeName = 1;</code>
     */
    com.google.protobuf.ByteString
        getStradeNameBytes();

    /**
     * <code>optional string OperaTime = 2;</code>
     */
    boolean hasOperaTime();
    /**
     * <code>optional string OperaTime = 2;</code>
     */
    String getOperaTime();
    /**
     * <code>optional string OperaTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getOperaTimeBytes();

    /**
     * <code>optional double LastStriceChoiceNum = 3 [default = 0];</code>
     */
    boolean hasLastStriceChoiceNum();
    /**
     * <code>optional double LastStriceChoiceNum = 3 [default = 0];</code>
     */
    double getLastStriceChoiceNum();

    /**
     * <code>optional double OperaStrictChoice = 4 [default = 0];</code>
     */
    boolean hasOperaStrictChoice();
    /**
     * <code>optional double OperaStrictChoice = 4 [default = 0];</code>
     */
    double getOperaStrictChoice();
  }
  /**
   * Protobuf type {@code com.jsj.member.ob.dto.proto.StrictChoices}
   */
  public static final class StrictChoices extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.jsj.member.ob.dto.proto.StrictChoices)
      StrictChoicesOrBuilder {
    // Use StrictChoices.newBuilder() to construct.
    private StrictChoices(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StrictChoices(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StrictChoices defaultInstance;
    public static StrictChoices getDefaultInstance() {
      return defaultInstance;
    }

    public StrictChoices getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StrictChoices(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              stradeName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              operaTime_ = bs;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              lastStriceChoiceNum_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              operaStrictChoice_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoices_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoices_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices.class, com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices.Builder.class);
    }

    public static com.google.protobuf.Parser<StrictChoices> PARSER =
        new com.google.protobuf.AbstractParser<StrictChoices>() {
      public StrictChoices parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StrictChoices(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<StrictChoices> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STRADENAME_FIELD_NUMBER = 1;
    private Object stradeName_;
    /**
     * <code>optional string StradeName = 1;</code>
     */
    public boolean hasStradeName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string StradeName = 1;</code>
     */
    public String getStradeName() {
      Object ref = stradeName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stradeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string StradeName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStradeNameBytes() {
      Object ref = stradeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stradeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIME_FIELD_NUMBER = 2;
    private Object operaTime_;
    /**
     * <code>optional string OperaTime = 2;</code>
     */
    public boolean hasOperaTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string OperaTime = 2;</code>
     */
    public String getOperaTime() {
      Object ref = operaTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operaTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string OperaTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOperaTimeBytes() {
      Object ref = operaTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operaTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTSTRICECHOICENUM_FIELD_NUMBER = 3;
    private double lastStriceChoiceNum_;
    /**
     * <code>optional double LastStriceChoiceNum = 3 [default = 0];</code>
     */
    public boolean hasLastStriceChoiceNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double LastStriceChoiceNum = 3 [default = 0];</code>
     */
    public double getLastStriceChoiceNum() {
      return lastStriceChoiceNum_;
    }

    public static final int OPERASTRICTCHOICE_FIELD_NUMBER = 4;
    private double operaStrictChoice_;
    /**
     * <code>optional double OperaStrictChoice = 4 [default = 0];</code>
     */
    public boolean hasOperaStrictChoice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double OperaStrictChoice = 4 [default = 0];</code>
     */
    public double getOperaStrictChoice() {
      return operaStrictChoice_;
    }

    private void initFields() {
      stradeName_ = "";
      operaTime_ = "";
      lastStriceChoiceNum_ = 0D;
      operaStrictChoice_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStradeNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOperaTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, lastStriceChoiceNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, operaStrictChoice_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStradeNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOperaTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lastStriceChoiceNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, operaStrictChoice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jsj.member.ob.dto.proto.StrictChoices}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jsj.member.ob.dto.proto.StrictChoices)
        com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoicesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoices_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoices_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices.class, com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices.Builder.class);
      }

      // Construct using com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stradeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        operaTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lastStriceChoiceNum_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        operaStrictChoice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.internal_static_com_jsj_member_ob_dto_proto_StrictChoices_descriptor;
      }

      public com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices getDefaultInstanceForType() {
        return com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices.getDefaultInstance();
      }

      public com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices build() {
        com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices buildPartial() {
        com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices result = new com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stradeName_ = stradeName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.operaTime_ = operaTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastStriceChoiceNum_ = lastStriceChoiceNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.operaStrictChoice_ = operaStrictChoice_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices) {
          return mergeFrom((com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices other) {
        if (other == com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices.getDefaultInstance()) return this;
        if (other.hasStradeName()) {
          bitField0_ |= 0x00000001;
          stradeName_ = other.stradeName_;
          onChanged();
        }
        if (other.hasOperaTime()) {
          bitField0_ |= 0x00000002;
          operaTime_ = other.operaTime_;
          onChanged();
        }
        if (other.hasLastStriceChoiceNum()) {
          setLastStriceChoiceNum(other.getLastStriceChoiceNum());
        }
        if (other.hasOperaStrictChoice()) {
          setOperaStrictChoice(other.getOperaStrictChoice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jsj.member.ob.dto.proto.StrictChoicesOuterClass.StrictChoices) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object stradeName_ = "";
      /**
       * <code>optional string StradeName = 1;</code>
       */
      public boolean hasStradeName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string StradeName = 1;</code>
       */
      public String getStradeName() {
        Object ref = stradeName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stradeName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string StradeName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStradeNameBytes() {
        Object ref = stradeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          stradeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string StradeName = 1;</code>
       */
      public Builder setStradeName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stradeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string StradeName = 1;</code>
       */
      public Builder clearStradeName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stradeName_ = getDefaultInstance().getStradeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string StradeName = 1;</code>
       */
      public Builder setStradeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stradeName_ = value;
        onChanged();
        return this;
      }

      private Object operaTime_ = "";
      /**
       * <code>optional string OperaTime = 2;</code>
       */
      public boolean hasOperaTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string OperaTime = 2;</code>
       */
      public String getOperaTime() {
        Object ref = operaTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            operaTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string OperaTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOperaTimeBytes() {
        Object ref = operaTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          operaTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string OperaTime = 2;</code>
       */
      public Builder setOperaTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        operaTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string OperaTime = 2;</code>
       */
      public Builder clearOperaTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        operaTime_ = getDefaultInstance().getOperaTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string OperaTime = 2;</code>
       */
      public Builder setOperaTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        operaTime_ = value;
        onChanged();
        return this;
      }

      private double lastStriceChoiceNum_ ;
      /**
       * <code>optional double LastStriceChoiceNum = 3 [default = 0];</code>
       */
      public boolean hasLastStriceChoiceNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double LastStriceChoiceNum = 3 [default = 0];</code>
       */
      public double getLastStriceChoiceNum() {
        return lastStriceChoiceNum_;
      }
      /**
       * <code>optional double LastStriceChoiceNum = 3 [default = 0];</code>
       */
      public Builder setLastStriceChoiceNum(double value) {
        bitField0_ |= 0x00000004;
        lastStriceChoiceNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double LastStriceChoiceNum = 3 [default = 0];</code>
       */
      public Builder clearLastStriceChoiceNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastStriceChoiceNum_ = 0D;
        onChanged();
        return this;
      }

      private double operaStrictChoice_ ;
      /**
       * <code>optional double OperaStrictChoice = 4 [default = 0];</code>
       */
      public boolean hasOperaStrictChoice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double OperaStrictChoice = 4 [default = 0];</code>
       */
      public double getOperaStrictChoice() {
        return operaStrictChoice_;
      }
      /**
       * <code>optional double OperaStrictChoice = 4 [default = 0];</code>
       */
      public Builder setOperaStrictChoice(double value) {
        bitField0_ |= 0x00000008;
        operaStrictChoice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double OperaStrictChoice = 4 [default = 0];</code>
       */
      public Builder clearOperaStrictChoice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        operaStrictChoice_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jsj.member.ob.dto.proto.StrictChoices)
    }

    static {
      defaultInstance = new StrictChoices(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jsj.member.ob.dto.proto.StrictChoices)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jsj_member_ob_dto_proto_StrictChoices_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jsj_member_ob_dto_proto_StrictChoices_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023StrictChoices.proto\022\033com.jsj.member.ob" +
      ".dto.proto\"t\n\rStrictChoices\022\022\n\nStradeNam" +
      "e\030\001 \001(\t\022\021\n\tOperaTime\030\002 \001(\t\022\036\n\023LastStrice" +
      "ChoiceNum\030\003 \001(\001:\0010\022\034\n\021OperaStrictChoice\030" +
      "\004 \001(\001:\0010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jsj_member_ob_dto_proto_StrictChoices_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jsj_member_ob_dto_proto_StrictChoices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_jsj_member_ob_dto_proto_StrictChoices_descriptor,
        new String[] { "StradeName", "OperaTime", "LastStriceChoiceNum", "OperaStrictChoice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
