// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZResponse.proto

package com.jsj.member.ob.dto.proto;

public final class ZResponseOuterClass {
  private ZResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ZResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jsj.member.dto.proto.ZResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes ZPack = 1;</code>
     */
    boolean hasZPack();
    /**
     * <code>optional bytes ZPack = 1;</code>
     */
    com.google.protobuf.ByteString getZPack();

    /**
     * <code>optional bool IsSuccess = 2 [default = false];</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>optional bool IsSuccess = 2 [default = false];</code>
     */
    boolean getIsSuccess();

    /**
     * <code>optional string ExceptionMessage = 3;</code>
     */
    boolean hasExceptionMessage();
    /**
     * <code>optional string ExceptionMessage = 3;</code>
     */
    String getExceptionMessage();
    /**
     * <code>optional string ExceptionMessage = 3;</code>
     */
    com.google.protobuf.ByteString
        getExceptionMessageBytes();
  }
  /**
   * Protobuf type {@code com.jsj.member.dto.proto.ZResponse}
   */
  public static final class ZResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.jsj.member.dto.proto.ZResponse)
      ZResponseOrBuilder {
    // Use ZResponse.newBuilder() to construct.
    private ZResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ZResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ZResponse defaultInstance;
    public static ZResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ZResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ZResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              zPack_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isSuccess_ = input.readBool();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              exceptionMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ZResponseOuterClass.internal_static_com_jsj_member_dto_proto_ZResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ZResponseOuterClass.internal_static_com_jsj_member_dto_proto_ZResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ZResponse.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ZResponse> PARSER =
        new com.google.protobuf.AbstractParser<ZResponse>() {
      public ZResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ZResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ZResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ZPACK_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString zPack_;
    /**
     * <code>optional bytes ZPack = 1;</code>
     */
    public boolean hasZPack() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes ZPack = 1;</code>
     */
    public com.google.protobuf.ByteString getZPack() {
      return zPack_;
    }

    public static final int ISSUCCESS_FIELD_NUMBER = 2;
    private boolean isSuccess_;
    /**
     * <code>optional bool IsSuccess = 2 [default = false];</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool IsSuccess = 2 [default = false];</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    public static final int EXCEPTIONMESSAGE_FIELD_NUMBER = 3;
    private Object exceptionMessage_;
    /**
     * <code>optional string ExceptionMessage = 3;</code>
     */
    public boolean hasExceptionMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ExceptionMessage = 3;</code>
     */
    public String getExceptionMessage() {
      Object ref = exceptionMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exceptionMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ExceptionMessage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionMessageBytes() {
      Object ref = exceptionMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        exceptionMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      zPack_ = com.google.protobuf.ByteString.EMPTY;
      isSuccess_ = false;
      exceptionMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, zPack_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isSuccess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getExceptionMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, zPack_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSuccess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getExceptionMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ZResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ZResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ZResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ZResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ZResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ZResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ZResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ZResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ZResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ZResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ZResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jsj.member.dto.proto.ZResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jsj.member.dto.proto.ZResponse)
        ZResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ZResponseOuterClass.internal_static_com_jsj_member_dto_proto_ZResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ZResponseOuterClass.internal_static_com_jsj_member_dto_proto_ZResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ZResponse.class, Builder.class);
      }

      // Construct using com.jsj.member.dto.proto.ZResponseOuterClass.ZResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        zPack_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        exceptionMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ZResponseOuterClass.internal_static_com_jsj_member_dto_proto_ZResponse_descriptor;
      }

      public ZResponse getDefaultInstanceForType() {
        return ZResponse.getDefaultInstance();
      }

      public ZResponse build() {
        ZResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ZResponse buildPartial() {
        ZResponse result = new ZResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.zPack_ = zPack_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.exceptionMessage_ = exceptionMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ZResponse) {
          return mergeFrom((ZResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ZResponse other) {
        if (other == ZResponse.getDefaultInstance()) return this;
        if (other.hasZPack()) {
          setZPack(other.getZPack());
        }
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasExceptionMessage()) {
          bitField0_ |= 0x00000004;
          exceptionMessage_ = other.exceptionMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ZResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ZResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString zPack_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes ZPack = 1;</code>
       */
      public boolean hasZPack() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes ZPack = 1;</code>
       */
      public com.google.protobuf.ByteString getZPack() {
        return zPack_;
      }
      /**
       * <code>optional bytes ZPack = 1;</code>
       */
      public Builder setZPack(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        zPack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ZPack = 1;</code>
       */
      public Builder clearZPack() {
        bitField0_ = (bitField0_ & ~0x00000001);
        zPack_ = getDefaultInstance().getZPack();
        onChanged();
        return this;
      }

      private boolean isSuccess_ ;
      /**
       * <code>optional bool IsSuccess = 2 [default = false];</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool IsSuccess = 2 [default = false];</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>optional bool IsSuccess = 2 [default = false];</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000002;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool IsSuccess = 2 [default = false];</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      private Object exceptionMessage_ = "";
      /**
       * <code>optional string ExceptionMessage = 3;</code>
       */
      public boolean hasExceptionMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ExceptionMessage = 3;</code>
       */
      public String getExceptionMessage() {
        Object ref = exceptionMessage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exceptionMessage_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ExceptionMessage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getExceptionMessageBytes() {
        Object ref = exceptionMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          exceptionMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ExceptionMessage = 3;</code>
       */
      public Builder setExceptionMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        exceptionMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ExceptionMessage = 3;</code>
       */
      public Builder clearExceptionMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        exceptionMessage_ = getDefaultInstance().getExceptionMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ExceptionMessage = 3;</code>
       */
      public Builder setExceptionMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        exceptionMessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jsj.member.dto.proto.ZResponse)
    }

    static {
      defaultInstance = new ZResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jsj.member.dto.proto.ZResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jsj_member_dto_proto_ZResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jsj_member_dto_proto_ZResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017ZResponse.proto\022\030com.jsj.member.dto.pr" +
      "oto\"N\n\tZResponse\022\r\n\005ZPack\030\001 \001(\014\022\030\n\tIsSuc" +
      "cess\030\002 \001(\010:\005false\022\030\n\020ExceptionMessage\030\003 " +
      "\001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jsj_member_dto_proto_ZResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jsj_member_dto_proto_ZResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_jsj_member_dto_proto_ZResponse_descriptor,
        new String[] { "ZPack", "IsSuccess", "ExceptionMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
